// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     /Users/shiruiwei/OurEra/android-tests/android-
//    utils/src/main/native/jni_generator.py
// For
//     com/example/tests/CodecStats

#ifndef com_example_tests_CodecStats_JNI
#define com_example_tests_CodecStats_JNI

#include <jni.h>
#include "../../../../vendor/autojni/base/jni_generator_helper.h"

// Step 1: forward declarations.
JNI_REGISTRATION_EXPORT extern const char
    kClassPath_com_example_tests_CodecStats_00024CodecsStatsInfb[];
const char kClassPath_com_example_tests_CodecStats_00024CodecsStatsInfb[] =
    "com/example/tests/CodecStats$CodecsStatsInfb";

JNI_REGISTRATION_EXPORT extern const char
    kClassPath_com_example_tests_CodecStats[];
const char kClassPath_com_example_tests_CodecStats[] =
    "com/example/tests/CodecStats";

// Leaking this jclass as we cannot use LazyInstance from some threads.
JNI_REGISTRATION_EXPORT base::subtle::AtomicWord
    g_com_example_tests_CodecStats_00024CodecsStatsInfb_clazz = 0;
#ifndef com_example_tests_CodecStats_00024CodecsStatsInfb_clazz_defined
#define com_example_tests_CodecStats_00024CodecsStatsInfb_clazz_defined
inline jclass com_example_tests_CodecStats_00024CodecsStatsInfb_clazz(JNIEnv*
    env) {
  return base::android::LazyGetClass(env,
      kClassPath_com_example_tests_CodecStats_00024CodecsStatsInfb,
      &g_com_example_tests_CodecStats_00024CodecsStatsInfb_clazz);
}
#endif

// Leaking this jclass as we cannot use LazyInstance from some threads.
JNI_REGISTRATION_EXPORT base::subtle::AtomicWord
    g_com_example_tests_CodecStats_clazz = 0;
#ifndef com_example_tests_CodecStats_clazz_defined
#define com_example_tests_CodecStats_clazz_defined
inline jclass com_example_tests_CodecStats_clazz(JNIEnv* env) {
  return base::android::LazyGetClass(env,
      kClassPath_com_example_tests_CodecStats,
      &g_com_example_tests_CodecStats_clazz);
}
#endif

// Step 2: method stubs.
JNI_GENERATOR_EXPORT jobject
    Java_com_example_tests_CodecStats_nativeGetStatsInfo(JNIEnv* env, jobject
    jcaller,
    jlong nativeCodecStats) {
  CodecStats* native = reinterpret_cast<CodecStats*>(nativeCodecStats);
  CHECK_NATIVE_PTR(env, jcaller, native, "GetStatsInfo", NULL);
  return native->GetStatsInfo(env, base::android::JavaParamRef<jobject>(env,
      jcaller)).Release();
}

static base::subtle::AtomicWord
    g_com_example_tests_CodecStats_00024CodecsStatsInfb_Constructor = 0;
static base::android::ScopedJavaLocalRef<jobject>
    Java_CodecsStatsInfb_Constructor(JNIEnv* env, const
    base::android::JavaRef<jstring>& name,
    JniIntWrapper width,
    JniIntWrapper height,
    JniIntWrapper bps,
    JniIntWrapper fps) {
  CHECK_CLAZZ(env, com_example_tests_CodecStats_00024CodecsStatsInfb_clazz(env),
      com_example_tests_CodecStats_00024CodecsStatsInfb_clazz(env), NULL);
  jmethodID method_id =
    base::android::MethodID::LazyGet<
      base::android::MethodID::TYPE_INSTANCE>(
      env, com_example_tests_CodecStats_00024CodecsStatsInfb_clazz(env),
      "<init>",
"("
"Ljava/lang/String;"
"I"
"I"
"I"
"I"
")"
"V",
      &g_com_example_tests_CodecStats_00024CodecsStatsInfb_Constructor);

  jobject ret =
env->NewObject(com_example_tests_CodecStats_00024CodecsStatsInfb_clazz(env),
          method_id, name.obj(), as_jint(width), as_jint(height), as_jint(bps),
              as_jint(fps));
  jni_generator::CheckException(env);
  return base::android::ScopedJavaLocalRef<jobject>(env, ret);
}

#endif  // com_example_tests_CodecStats_JNI

